//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicantProfile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicantProfile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindJobs.Resources.Resx.en.ApplicantProfile", typeof(ApplicantProfile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional section.
        /// </summary>
        public static string Additionalsection {
            get {
                return ResourceManager.GetString("Additionalsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Section Add Successfully.
        /// </summary>
        public static string AdditionalSectionAddSuccessfully {
            get {
                return ResourceManager.GetString("AdditionalSectionAddSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advantage / OptionalKnowledge.
        /// </summary>
        public static string AdvantageOrOptionalKnowledge {
            get {
                return ResourceManager.GetString("AdvantageOrOptionalKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement.
        /// </summary>
        public static string agreement {
            get {
                return ResourceManager.GetString("agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied Jobs.
        /// </summary>
        public static string AppliedJos {
            get {
                return ResourceManager.GetString("AppliedJos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASAP.
        /// </summary>
        public static string ASAP {
            get {
                return ResourceManager.GetString("ASAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability .
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvailableDate.
        /// </summary>
        public static string AvailableDate {
            get {
                return ResourceManager.GetString("AvailableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        public static string Beginner {
            get {
                return ResourceManager.GetString("Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string Bus {
            get {
                return ResourceManager.GetString("Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant Get Information From Server.
        /// </summary>
        public static string cantFetchData {
            get {
                return ResourceManager.GetString("cantFetchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        public static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choice the city.
        /// </summary>
        public static string ChoiceTheCity {
            get {
                return ResourceManager.GetString("ChoiceTheCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice the country.
        /// </summary>
        public static string ChoiceTheCountry {
            get {
                return ResourceManager.GetString("ChoiceTheCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice Licence.
        /// </summary>
        public static string ChoiceTheLicence {
            get {
                return ResourceManager.GetString("ChoiceTheLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice Your Document.
        /// </summary>
        public static string ChoiceYourDocument {
            get {
                return ResourceManager.GetString("ChoiceYourDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language and apperance.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City or Location.
        /// </summary>
        public static string CityLocation {
            get {
                return ResourceManager.GetString("CityLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Detail.
        /// </summary>
        public static string ContactDetail {
            get {
                return ResourceManager.GetString("ContactDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Detail Add Successfully.
        /// </summary>
        public static string ContactDetailAddSuccessfully {
            get {
                return ResourceManager.GetString("ContactDetailAddSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country .
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course or Certificate.
        /// </summary>
        public static string CourseOrCertificate {
            get {
                return ResourceManager.GetString("CourseOrCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cover Letter.
        /// </summary>
        public static string CoverLetter {
            get {
                return ResourceManager.GetString("CoverLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV.
        /// </summary>
        public static string CV {
            get {
                return ResourceManager.GetString("CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cv Language.
        /// </summary>
        public static string CvLanguage {
            get {
                return ResourceManager.GetString("CvLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Delete This Item.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Add Successfully.
        /// </summary>
        public static string DocumentAddSuccessfully {
            get {
                return ResourceManager.GetString("DocumentAddSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select image with size less than 10mg.
        /// </summary>
        public static string DocumentSizeMoreThan10 {
            get {
                return ResourceManager.GetString("DocumentSizeMoreThan10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Document Add Successfully.
        /// </summary>
        public static string DocumentUploadSuccessfully {
            get {
                return ResourceManager.GetString("DocumentUploadSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download as csv.
        /// </summary>
        public static string DownloadasCSV {
            get {
                return ResourceManager.GetString("DownloadasCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download as pdf.
        /// </summary>
        public static string Downloadaspdf {
            get {
                return ResourceManager.GetString("Downloadaspdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want Delete This Record?.
        /// </summary>
        public static string DoYouWandDeleteThisRecord {
            get {
                return ResourceManager.GetString("DoYouWandDeleteThisRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr.
        /// </summary>
        public static string Dr {
            get {
                return ResourceManager.GetString("Dr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving.
        /// </summary>
        public static string Driving {
            get {
                return ResourceManager.GetString("Driving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving license.
        /// </summary>
        public static string Drivinglicense {
            get {
                return ResourceManager.GetString("Drivinglicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Add Successfully.
        /// </summary>
        public static string EducationAddSuccessfully {
            get {
                return ResourceManager.GetString("EducationAddSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Level.
        /// </summary>
        public static string EducationLevel {
            get {
                return ResourceManager.GetString("EducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Prefernces.
        /// </summary>
        public static string EmailPrefernces {
            get {
                return ResourceManager.GetString("EmailPrefernces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        public static string Employer {
            get {
                return ResourceManager.GetString("Employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Range.
        /// </summary>
        public static string EnterRange {
            get {
                return ResourceManager.GetString("EnterRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European Union.
        /// </summary>
        public static string EuropeanUnion {
            get {
                return ResourceManager.GetString("EuropeanUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your File Choise Is Not Image Or Pdf.
        /// </summary>
        public static string FileIsNotImage {
            get {
                return ResourceManager.GetString("FileIsNotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First and Last Name.
        /// </summary>
        public static string First_and_Last_Name {
            get {
                return ResourceManager.GetString("First and Last Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForAllUsers.
        /// </summary>
        public static string ForAllUsers {
            get {
                return ResourceManager.GetString("ForAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freelancer.
        /// </summary>
        public static string Freelancer {
            get {
                return ResourceManager.GetString("Freelancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full time.
        /// </summary>
        public static string Full_time {
            get {
                return ResourceManager.GetString("Full time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High School.
        /// </summary>
        public static string HighSchool {
            get {
                return ResourceManager.GetString("HighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly.
        /// </summary>
        public static string Hourly {
            get {
                return ResourceManager.GetString("Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string Hybrid {
            get {
                return ResourceManager.GetString("Hybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I currently work here.
        /// </summary>
        public static string Icurrentlyworkhere {
            get {
                return ResourceManager.GetString("Icurrentlyworkhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Not Uploaded Please Contact With Admin.
        /// </summary>
        public static string ImageNotUploade {
            get {
                return ResourceManager.GetString("ImageNotUploade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Image Size Is More Than 10MB.
        /// </summary>
        public static string ImageSizeError {
            get {
                return ResourceManager.GetString("ImageSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Uploaded Successfully.
        /// </summary>
        public static string ImageUploadSuccessfully {
            get {
                return ResourceManager.GetString("ImageUploadSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        public static string Intermediate {
            get {
                return ResourceManager.GetString("Intermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internship.
        /// </summary>
        public static string Internship {
            get {
                return ResourceManager.GetString("Internship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobAllert.
        /// </summary>
        public static string JobAllert {
            get {
                return ResourceManager.GetString("JobAllert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobPosition.
        /// </summary>
        public static string JobPosition {
            get {
                return ResourceManager.GetString("JobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge.
        /// </summary>
        public static string Knowledge {
            get {
                return ResourceManager.GetString("Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Add Successfully.
        /// </summary>
        public static string KnowledgeAddSuccessfully {
            get {
                return ResourceManager.GetString("KnowledgeAddSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Level.
        /// </summary>
        public static string KnowledgeLevel {
            get {
                return ResourceManager.GetString("KnowledgeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Add Successfully.
        /// </summary>
        public static string LanguageAddSuccessfully {
            get {
                return ResourceManager.GetString("LanguageAddSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language Level.
        /// </summary>
        public static string languageLevel {
            get {
                return ResourceManager.GetString("languageLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Vehicles.
        /// </summary>
        public static string LargeVehicles {
            get {
                return ResourceManager.GetString("LargeVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minibus.
        /// </summary>
        public static string Minibus {
            get {
                return ResourceManager.GetString("Minibus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycles.
        /// </summary>
        public static string Motorcycles {
            get {
                return ResourceManager.GetString("Motorcycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyJob.
        /// </summary>
        public static string MyJob {
            get {
                return ResourceManager.GetString("MyJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotAvailabeUntil.
        /// </summary>
        public static string NotAvailabeUntil {
            get {
                return ResourceManager.GetString("NotAvailabeUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available Until.
        /// </summary>
        public static string NotAvailableUntil {
            get {
                return ResourceManager.GetString("NotAvailableUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Information Not Save.
        /// </summary>
        public static string NotSaveSuccessfully {
            get {
                return ResourceManager.GetString("NotSaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Successfully Update.
        /// </summary>
        public static string NotSuccessfullyUpdate {
            get {
                return ResourceManager.GetString("NotSuccessfullyUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlyForRegistered.
        /// </summary>
        public static string OnlyForRegistered {
            get {
                return ResourceManager.GetString("OnlyForRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnRequest.
        /// </summary>
        public static string OnRequest {
            get {
                return ResourceManager.GetString("OnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office (on-site).
        /// </summary>
        public static string OnSite {
            get {
                return ResourceManager.GetString("OnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Document.
        /// </summary>
        public static string OtherDocument {
            get {
                return ResourceManager.GetString("OtherDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part time.
        /// </summary>
        public static string Part_time {
            get {
                return ResourceManager.GetString("Part time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per.
        /// </summary>
        public static string Per {
            get {
                return ResourceManager.GetString("Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information Add Successfully.
        /// </summary>
        public static string PersonalInformationAddSuccessfully {
            get {
                return ResourceManager.GetString("PersonalInformationAddSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Phone Number Is Not Valid.
        /// </summary>
        public static string PhoneNumberNotValid {
            get {
                return ResourceManager.GetString("PhoneNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code / Zip.
        /// </summary>
        public static string PostCode_Zip {
            get {
                return ResourceManager.GetString("PostCode/Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefered place of work.
        /// </summary>
        public static string Prefered_place_of_work {
            get {
                return ResourceManager.GetString("Prefered place of work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefered type of work.
        /// </summary>
        public static string Prefered_type_of_work {
            get {
                return ResourceManager.GetString("Prefered type of work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Visible.
        /// </summary>
        public static string Profile_Visible {
            get {
                return ResourceManager.GetString("Profile Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Detail.
        /// </summary>
        public static string ProfileDetail {
            get {
                return ResourceManager.GetString("ProfileDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Type.
        /// </summary>
        public static string RateType {
            get {
                return ResourceManager.GetString("RateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rather not to say.
        /// </summary>
        public static string RatherNotToSay {
            get {
                return ResourceManager.GetString("RatherNotToSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Junior Knowledge.
        /// </summary>
        public static string RequiredJuniorKnowledge {
            get {
                return ResourceManager.GetString("RequiredJuniorKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Senior knowledge.
        /// </summary>
        public static string RequiredSeniorknowledge {
            get {
                return ResourceManager.GetString("RequiredSeniorknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Information Save Successfully.
        /// </summary>
        public static string SaveSuccessfully {
            get {
                return ResourceManager.GetString("SaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchEngines.
        /// </summary>
        public static string SearchEngines {
            get {
                return ResourceManager.GetString("SearchEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Document File.
        /// </summary>
        public static string SelectDocumentFile {
            get {
                return ResourceManager.GetString("SelectDocumentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Your Document.
        /// </summary>
        public static string SelectYourDocument {
            get {
                return ResourceManager.GetString("SelectYourDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string sex {
            get {
                return ResourceManager.GetString("sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Writing.
        /// </summary>
        public static string StartWriting {
            get {
                return ResourceManager.GetString("StartWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string StreetAddress {
            get {
                return ResourceManager.GetString("StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest.
        /// </summary>
        public static string Suggest {
            get {
                return ResourceManager.GetString("Suggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        public static string Switzerland {
            get {
                return ResourceManager.GetString("Switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show My Address in Profile.
        /// </summary>
        public static string TextAddress {
            get {
                return ResourceManager.GetString("TextAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show My Age in Profile.
        /// </summary>
        public static string TextAge {
            get {
                return ResourceManager.GetString("TextAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show My Country/City in Profile.
        /// </summary>
        public static string TextCountryOrCity {
            get {
                return ResourceManager.GetString("TextCountryOrCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show My Gender in Profile.
        /// </summary>
        public static string TextGender {
            get {
                return ResourceManager.GetString("TextGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show My Nationality On Profile.
        /// </summary>
        public static string TextNationality {
            get {
                return ResourceManager.GetString("TextNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show My Phone in Profile.
        /// </summary>
        public static string TextPhone {
            get {
                return ResourceManager.GetString("TextPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profiles should be found in search Engines.
        /// </summary>
        public static string TextSearchEngines {
            get {
                return ResourceManager.GetString("TextSearchEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Document!.
        /// </summary>
        public static string ThereIsNoDocumentUploaded {
            get {
                return ResourceManager.GetString("ThereIsNoDocumentUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Education!.
        /// </summary>
        public static string ThereIsNoEducation {
            get {
                return ResourceManager.GetString("ThereIsNoEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Knowledge!.
        /// </summary>
        public static string ThereIsNoKnowledge {
            get {
                return ResourceManager.GetString("ThereIsNoKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Language!.
        /// </summary>
        public static string ThereIsNoLanguage {
            get {
                return ResourceManager.GetString("ThereIsNoLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Work Experience!.
        /// </summary>
        public static string ThereIsNoWorkExperience {
            get {
                return ResourceManager.GetString("ThereIsNoWorkExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        public static string UnitedStates {
            get {
                return ResourceManager.GetString("UnitedStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string University {
            get {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University/Institute Name.
        /// </summary>
        public static string University_InstituteName {
            get {
                return ResourceManager.GetString("University/InstituteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information updated successfully.
        /// </summary>
        public static string UpdateSuccessfully {
            get {
                return ResourceManager.GetString("UpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Documents.
        /// </summary>
        public static string UploadDocuments {
            get {
                return ResourceManager.GetString("UploadDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Permit.
        /// </summary>
        public static string Work_Permit {
            get {
                return ResourceManager.GetString("Work Permit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Experience.
        /// </summary>
        public static string WorkExperience {
            get {
                return ResourceManager.GetString("WorkExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Experience Add Successfully.
        /// </summary>
        public static string WorkExperienceAddSuccessfully {
            get {
                return ResourceManager.GetString("WorkExperienceAddSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work From Home.
        /// </summary>
        public static string WorkFromHome {
            get {
                return ResourceManager.GetString("WorkFromHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work from home (off-site).
        /// </summary>
        public static string Workfromhomeoffsite {
            get {
                return ResourceManager.GetString("Workfromhomeoffsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Only Upload 6 Document.
        /// </summary>
        public static string YouCanOnlyUploadSixDocument {
            get {
                return ResourceManager.GetString("YouCanOnlyUploadSixDocument", resourceCulture);
            }
        }
    }
}
