//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CompanyOffer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyOffer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindJobs.Resources.Resx.en.CompanyOffer", typeof(CompanyOffer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Offer.
        /// </summary>
        public static string Add_Offer {
            get {
                return ResourceManager.GetString("Add Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional section.
        /// </summary>
        public static string Additional_section {
            get {
                return ResourceManager.GetString("Additional section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Salary.
        /// </summary>
        public static string AdditionalSalary {
            get {
                return ResourceManager.GetString("AdditionalSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Of Work.
        /// </summary>
        public static string AddressOfWork {
            get {
                return ResourceManager.GetString("AddressOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional/Advantage Knowledge.
        /// </summary>
        public static string Advantage_OptionalKnowledge {
            get {
                return ResourceManager.GetString("Advantage/OptionalKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement.
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of  selected language.
        /// </summary>
        public static string At_least_one_of__selected_language {
            get {
                return ResourceManager.GetString("At least one of  selected language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Price Should be lower Than Upper Price.
        /// </summary>
        public static string BasicPriceValidation {
            get {
                return ResourceManager.GetString("BasicPriceValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Salary.
        /// </summary>
        public static string BasicSalary {
            get {
                return ResourceManager.GetString("BasicSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benifits.
        /// </summary>
        public static string Benifits {
            get {
                return ResourceManager.GetString("Benifits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filters.
        /// </summary>
        public static string ClearFilters {
            get {
                return ResourceManager.GetString("ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication.
        /// </summary>
        public static string CompanyPublication {
            get {
                return ResourceManager.GetString("CompanyPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Profile.
        /// </summary>
        public static string Complete_Profile {
            get {
                return ResourceManager.GetString("Complete Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Licence.
        /// </summary>
        public static string DrivingLicence {
            get {
                return ResourceManager.GetString("DrivingLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Didnt Save , Please Call With Admin.
        /// </summary>
        public static string ErrorSave {
            get {
                return ResourceManager.GetString("ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        public static string Favourites {
            get {
                return ResourceManager.GetString("Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Days Ago.
        /// </summary>
        public static string FiveDaysAgo {
            get {
                return ResourceManager.GetString("FiveDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Department.
        /// </summary>
        public static string FocusDepartment {
            get {
                return ResourceManager.GetString("FocusDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For 1 Month.
        /// </summary>
        public static string ForOneMonth {
            get {
                return ResourceManager.GetString("ForOneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For 1 Week.
        /// </summary>
        public static string ForOneWeek {
            get {
                return ResourceManager.GetString("ForOneWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For 2 Months.
        /// </summary>
        public static string ForTwoMonths {
            get {
                return ResourceManager.GetString("ForTwoMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For 2 Weeks.
        /// </summary>
        public static string ForTwoWeeks {
            get {
                return ResourceManager.GetString("ForTwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Days Ago.
        /// </summary>
        public static string FourDaysAgo {
            get {
                return ResourceManager.GetString("FourDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freelancer.
        /// </summary>
        public static string Freelancer {
            get {
                return ResourceManager.GetString("Freelancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full time.
        /// </summary>
        public static string FullTime {
            get {
                return ResourceManager.GetString("FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher education Level 1.
        /// </summary>
        public static string HighereducationLevel1 {
            get {
                return ResourceManager.GetString("HighereducationLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher education Level 2.
        /// </summary>
        public static string HighereducationLevel2 {
            get {
                return ResourceManager.GetString("HighereducationLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher education Level 3.
        /// </summary>
        public static string HighereducationLevel3 {
            get {
                return ResourceManager.GetString("HighereducationLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High schooll student.
        /// </summary>
        public static string Highschoollstudent {
            get {
                return ResourceManager.GetString("Highschoollstudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intership.
        /// </summary>
        public static string InternShip {
            get {
                return ResourceManager.GetString("InternShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description.
        /// </summary>
        public static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Position.
        /// </summary>
        public static string JobPosition {
            get {
                return ResourceManager.GetString("JobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnowLedage And Requirements.
        /// </summary>
        public static string KnowLedageAndRequirements {
            get {
                return ResourceManager.GetString("KnowLedageAndRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge and level.
        /// </summary>
        public static string Knowledgeandlevel {
            get {
                return ResourceManager.GetString("Knowledgeandlevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language and level.
        /// </summary>
        public static string Languageandlevel {
            get {
                return ResourceManager.GetString("Languageandlevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Skills.
        /// </summary>
        public static string LanguageSkills {
            get {
                return ResourceManager.GetString("LanguageSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe partially.
        /// </summary>
        public static string MaybePartially {
            get {
                return ResourceManager.GetString("MaybePartially", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicroSoft Word.
        /// </summary>
        public static string MicroSoftWord {
            get {
                return ResourceManager.GetString("MicroSoftWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need culture language (Country language).
        /// </summary>
        public static string No_need_culture_language__Country_language_ {
            get {
                return ResourceManager.GetString("No need culture language (Country language)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Offer With Your Filter.
        /// </summary>
        public static string NoFilterExists {
            get {
                return ResourceManager.GetString("NoFilterExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of years experince.
        /// </summary>
        public static string Numberofyearsexperince {
            get {
                return ResourceManager.GetString("Numberofyearsexperince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Added to your Favourit List.
        /// </summary>
        public static string OfferAddedtoyourFavourit_List {
            get {
                return ResourceManager.GetString("OfferAddedtoyourFavourit List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Day Ago.
        /// </summary>
        public static string OneDayAgo {
            get {
                return ResourceManager.GetString("OneDayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Month Ago.
        /// </summary>
        public static string OneMonthAgo {
            get {
                return ResourceManager.GetString("OneMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Weeks Ago.
        /// </summary>
        public static string OneWeeksAgo {
            get {
                return ResourceManager.GetString("OneWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Language Skills.
        /// </summary>
        public static string OptionalLanguageSkills {
            get {
                return ResourceManager.GetString("OptionalLanguageSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Information.
        /// </summary>
        public static string OtherInformation {
            get {
                return ResourceManager.GetString("OtherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Knowledge.
        /// </summary>
        public static string OtherKnowledge {
            get {
                return ResourceManager.GetString("OtherKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Work From Home.
        /// </summary>
        public static string PartialWorkFromHome {
            get {
                return ResourceManager.GetString("PartialWorkFromHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part time.
        /// </summary>
        public static string PartTime {
            get {
                return ResourceManager.GetString("PartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with PayPal.
        /// </summary>
        public static string PayPal {
            get {
                return ResourceManager.GetString("PayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per.
        /// </summary>
        public static string Per {
            get {
                return ResourceManager.GetString("Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place of work.
        /// </summary>
        public static string placeofwork {
            get {
                return ResourceManager.GetString("placeofwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Description.
        /// </summary>
        public static string PositionDescription {
            get {
                return ResourceManager.GetString("PositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Secondary.
        /// </summary>
        public static string PostSecondary {
            get {
                return ResourceManager.GetString("PostSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary education.
        /// </summary>
        public static string Primary_education {
            get {
                return ResourceManager.GetString("Primary education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication.
        /// </summary>
        public static string Publication {
            get {
                return ResourceManager.GetString("Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Junior Knowledge.
        /// </summary>
        public static string RequiredJuniorKnowledge {
            get {
                return ResourceManager.GetString("RequiredJuniorKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Language Skills.
        /// </summary>
        public static string RequiredLanguageSkills {
            get {
                return ResourceManager.GetString("RequiredLanguageSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Senior knowledge.
        /// </summary>
        public static string RequiredSeniorknowledge {
            get {
                return ResourceManager.GetString("RequiredSeniorknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirments Per Employee.
        /// </summary>
        public static string RequirementsPerEmployee {
            get {
                return ResourceManager.GetString("RequirementsPerEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires knowledge  of all selected language.
        /// </summary>
        public static string Requires_knowledge__of_all_selected_language {
            get {
                return ResourceManager.GetString("Requires knowledge  of all selected language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Offer Save Successfully.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary schooll with graduation.
        /// </summary>
        public static string Secondaryschoollwithgraduation {
            get {
                return ResourceManager.GetString("Secondaryschoollwithgraduation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary schooll without graduation.
        /// </summary>
        public static string Secondaryschoollwithoutgraduation {
            get {
                return ResourceManager.GetString("Secondaryschoollwithoutgraduation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Language.
        /// </summary>
        public static string selectALanguage {
            get {
                return ResourceManager.GetString("selectALanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a level.
        /// </summary>
        public static string selectAlevel {
            get {
                return ResourceManager.GetString("selectAlevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Cv By Email.
        /// </summary>
        public static string SendCvByEmail {
            get {
                return ResourceManager.GetString("SendCvByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Salary to Applicant.
        /// </summary>
        public static string ShowApplicantsSalary {
            get {
                return ResourceManager.GetString("ShowApplicantsSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Offer Registered For your JobCategories Or Location.
        /// </summary>
        public static string ThereIsNoOfferRegisteredForyourJobCategoriesOrLocation {
            get {
                return ResourceManager.GetString("ThereIsNoOfferRegisteredForyourJobCategoriesOrLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Field Is Required.
        /// </summary>
        public static string ThisFieldIsRequired {
            get {
                return ResourceManager.GetString("ThisFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Days Ago.
        /// </summary>
        public static string ThreeDaysAgo {
            get {
                return ResourceManager.GetString("ThreeDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDay.
        /// </summary>
        public static string ToDay {
            get {
                return ResourceManager.GetString("ToDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Requirement.
        /// </summary>
        public static string TravelRequirement {
            get {
                return ResourceManager.GetString("TravelRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Days Ago.
        /// </summary>
        public static string TwoDaysAgo {
            get {
                return ResourceManager.GetString("TwoDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Months Ago.
        /// </summary>
        public static string TwoMonthsAgo {
            get {
                return ResourceManager.GetString("TwoMonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Weeks Ago.
        /// </summary>
        public static string TwoWeeksAgo {
            get {
                return ResourceManager.GetString("TwoWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Contract.
        /// </summary>
        public static string TypeOfContract {
            get {
                return ResourceManager.GetString("TypeOfContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of employment.
        /// </summary>
        public static string Typeofemployment {
            get {
                return ResourceManager.GetString("Typeofemployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University student.
        /// </summary>
        public static string UniversityStudent {
            get {
                return ResourceManager.GetString("UniversityStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Limit.
        /// </summary>
        public static string UpperLimit {
            get {
                return ResourceManager.GetString("UpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage Conditions.
        /// </summary>
        public static string WageConditions {
            get {
                return ResourceManager.GetString("WageConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work at the Regular Work place.
        /// </summary>
        public static string WorkAtTheRegularWorkPlace {
            get {
                return ResourceManager.GetString("WorkAtTheRegularWorkPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working From Home.
        /// </summary>
        public static string WorkingFromHome {
            get {
                return ResourceManager.GetString("WorkingFromHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work only at the workplace.
        /// </summary>
        public static string WorkOnlyAtTheWorkplace {
            get {
                return ResourceManager.GetString("WorkOnlyAtTheWorkplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work only from home.
        /// </summary>
        public static string WorkOnlyFromHome {
            get {
                return ResourceManager.GetString("WorkOnlyFromHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Requires Travell.
        /// </summary>
        public static string WorkRequiresTravell {
            get {
                return ResourceManager.GetString("WorkRequiresTravell", resourceCulture);
            }
        }
    }
}
