//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Cv {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cv() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindJobs.Resources.Resx.en.Cv", typeof(Cv).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose Appearance.
        /// </summary>
        public static string ChoseAppearance {
            get {
                return ResourceManager.GetString("ChoseAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose.
        /// </summary>
        public static string choseCv {
            get {
                return ResourceManager.GetString("choseCv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose Document.
        /// </summary>
        public static string ChoseDoc {
            get {
                return ResourceManager.GetString("ChoseDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download it in PDF format and respond to job offers with it .You can change the look at any time ..
        /// </summary>
        public static string CvText {
            get {
                return ResourceManager.GetString("CvText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education And Qualifications.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledges.
        /// </summary>
        public static string Knowledges {
            get {
                return ResourceManager.GetString("Knowledges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not employed.
        /// </summary>
        public static string notemployed {
            get {
                return ResourceManager.GetString("notemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommend friend.
        /// </summary>
        public static string RecommandToFrinde {
            get {
                return ResourceManager.GetString("RecommandToFrinde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send your Cv.
        /// </summary>
        public static string SendCv {
            get {
                return ResourceManager.GetString("SendCv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still Wokring.
        /// </summary>
        public static string StillWokring {
            get {
                return ResourceManager.GetString("StillWokring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your own document.
        /// </summary>
        public static string UploaYourOwn {
            get {
                return ResourceManager.GetString("UploaYourOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Experincees.
        /// </summary>
        public static string WorkExperincees {
            get {
                return ResourceManager.GetString("WorkExperincees", resourceCulture);
            }
        }
    }
}
