//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Payment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Payment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindJobs.Resources.Resx.en.Payment", typeof(Payment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payable amount is incorrect or it&apos;s already paid..
        /// </summary>
        public static string AlreadyPaid {
            get {
                return ResourceManager.GetString("AlreadyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Payment Method.
        /// </summary>
        public static string ChoosePayment {
            get {
                return ResourceManager.GetString("ChoosePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompleteText.
        /// </summary>
        public static string Complete_Text {
            get {
                return ResourceManager.GetString("Complete Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Connection to the payment gateway cannot be stablished. Please try again later..
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrditCard.
        /// </summary>
        public static string CrditCard {
            get {
                return ResourceManager.GetString("CrditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customer.
        /// </summary>
        public static string DearCustomer {
            get {
                return ResourceManager.GetString("DearCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Payment.
        /// </summary>
        public static string GoToPayment {
            get {
                return ResourceManager.GetString("GoToPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no order to checkout..
        /// </summary>
        public static string NoOrder {
            get {
                return ResourceManager.GetString("NoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentFailure.
        /// </summary>
        public static string PaymentFailure {
            get {
                return ResourceManager.GetString("PaymentFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentSuccess.
        /// </summary>
        public static string PaymentSuccess {
            get {
                return ResourceManager.GetString("PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal.
        /// </summary>
        public static string PayPalText {
            get {
                return ResourceManager.GetString("PayPalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your order..
        /// </summary>
        public static string ThankYouForYourOrder {
            get {
                return ResourceManager.GetString("ThankYouForYourOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This payment has already been processed.
        /// </summary>
        public static string ThisPaymentHasAlreadyBeenProcessed {
            get {
                return ResourceManager.GetString("ThisPaymentHasAlreadyBeenProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By CrditCard.
        /// </summary>
        public static string UseCrditCard {
            get {
                return ResourceManager.GetString("UseCrditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Paypal.
        /// </summary>
        public static string UsePaypal {
            get {
                return ResourceManager.GetString("UsePaypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to process your payment.
        /// </summary>
        public static string WeAreUnableToProcessYourPayment {
            get {
                return ResourceManager.GetString("WeAreUnableToProcessYourPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot find your order to pay..
        /// </summary>
        public static string WeCannotFindYourOrderToPay {
            get {
                return ResourceManager.GetString("WeCannotFindYourOrderToPay", resourceCulture);
            }
        }
    }
}
